### PR TITLE
Replace embedded editorconfig-core-py with submodule.

### LINKED ISSUE #11: EditorConfig core submodule too old
The version is still 3 years ago.

### PR DESCRIPTION
**Pull request by mcepl**
Fixes #11 

What about this?

### CODE REVIEW

**Comment by xuhdev** [comment]
Thanks. @treyhunner Do you remember the reason that we didn't use submodule here?

**Comment by treyhunner** [comment]
@xuhdev I do not. I'm guessing I didn't do a submodule originally because vendoring the code more directly makes it easier to retrieve for those checking it out from GitHub (no need to do anything beyond just a git clone). Also the auto-generated ZIP files on GitHub probably won't have the core library.

As long as we can (and make sure to) manually bundle the core library in the ZIP files when we put those on GitHub for download, I think this might be fine.

**Comment by mcepl** [comment]
Well, that's the question how do you imagine the standard way of delivering plugins for gedit is. For example with vim, it is now (even officially with vim8) having directory with directories per plugin (they given be git submodules of one big ~/.vim/ git repo). Or that ``install.sh`` should actually make **symlinks** not copy of the files, so you can still update just by ``git pull``.

**Comment by xuhdev** [comment]
I remembered why, it is a subtree. Update the directory using

    git subtree pull --prefix editorconfig-core-py https://github.com/editorconfig/editorconfig-core-py master

**Pull request closed without merging**
